export const FETCH_ALL_PERSON = "FETCH_ALL_PERSON";
export const DELETE_SINGLE_PERSON = "DELETE_SINGLE_PERSON";
export const UPDATE_SINGLE_PERSON = "UPDATE_SINGLE_PERSON";
export const FETCH_SINGLE_PERSON = "FETCH_SINGLE_PERSON";
export const ADD_SINGLE_PERSON = "ADD_SINGLE_PERSON";
